name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (prod/dev)'
        required: true
      branch:
        description: 'Branch name'
        required: true

jobs:
  validation:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.check_env.outputs.environment }}
    steps:
      - name: Validate environment input
        id: check_env
        run: |
          # Check if the environment is either 'prod' or 'dev'
          if [[ "${{ github.event.inputs.environment }}" != "prod" && "${{ github.event.inputs.environment }}" != "dev" ]]; then
            echo "Error: Environment must be 'prod' or 'dev'."
            exit 1
          fi
          # Additional check for 'prod' deployment to be from 'main' branch only
          if [[ "${{ github.event.inputs.environment }}" == "prod" && "${{ github.event.inputs.branch }}" != "main" ]]; then
            echo "Error: Production deployments can only be made from the 'main' branch."
            exit 1
          fi

  deploy:
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Execute Remote Deployment Script
        run: ssh -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.SERVER_HOST }} "bash /home/${{ secrets.USERNAME }}/deploy.sh ${{ github.event.inputs.branch }} ${{ github.event.inputs.environment }}"
